version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sa_rest
      # MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  sample:
    depends_on:
      - db
    image: luchob/docker-sample:v3
    ports:
      - "80:8080"

volumes:
  db_data: {}
